# Generated by Django 5.0.1 on 2026-01-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_featuredimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='image',
            field=models.ImageField(help_text='Recommended: 1280x720 (16:9)', upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
