# Generated by Django 5.0.1 on 2026-01-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_rename_pos_expense_date_idx_pos_expense_date_467b66_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
